steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'FUNCTION_NAME', '--runtime', 'RUNTIME', '--trigger-http', '--entry-point', 'ENTRY_POINT', '--source', 'SOURCE', '--memory', '256MB', '--timeout', '60s', '--region', 'us-central1', '--allow-unauthenticated']
  env:
  - 'GOOGLE_CLOUD_PROJECT=$(project-id)'
  - 'FUNCTION_NAME=helloPubSub'
  - 'RUNTIME=nodejs16'
  - 'ENTRY_POINT=helloPubSub'
  - 'SOURCE=./'
  - 'REGION=us-central1'