steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'FUNCTION_NAME', '--runtime', 'RUNTIME', '--trigger-http', '--entry-point', 'ENTRY_POINT', '--source', 'SOURCE', '--memory', 'MEMORY', '--timeout', 'TIMEOUT', '--region', 'REGION', '--allow-unauthenticated']
  env:
  - 'GOOGLE_CLOUD_PROJECT=$(project-id)'
  - 'FUNCTION_NAME=helloPubSub'
  - 'RUNTIME=nodejs16'
  - 'ENTRY_POINT=helloPubSub'
  - 'SOURCE=./'
  - 'MEMORY=256MB'
  - 'TIMEOUT=60'
  - 'REGION=us-central1'